### PR TITLE
Add Fix workflow

### PR DESCRIPTION
**Pull request by yschimke**
Runnable on a fork of the repository such as

https://github.com/yschimke/ComposeOClock/actions/workflows/fix_workflow.yaml

When run on a branch, generates updated screenshots and commits them.

Example https://github.com/yschimke/ComposeOClock/actions/runs/8030224947

### CODE REVIEW

**Comment by yschimke** [comment]
Diffs should be one offs from running on ubuntu-latest https://github.com/Splitties/ComposeOClock/pull/6/commits/e32c56b49ccbff1c9e1ca942423e9d9a270f3bea

**Comment by LouisCAD** [comment]
Do you know why the resulting screenshots are different, yet looking the same to the eye?

**Comment by yschimke** [comment]
Well known differences across all platforms

https://proandroiddev.com/oh-snap-966bd786b7a4

https://www.linkedin.com/pulse/easy-screenshot-testing-droidcon-london-jose-alc%C3%A9rreca-cz0dc

image

**Comment by yschimke** [comment]
More canonical link https://github.com/robolectric/robolectric/issues/8457

**Comment by LouisCAD** [comment]
Hum… this mismatch is not such an ideal situation…
I'd like the workflow to not be so dependent on GitHub actions or a specific desktop OS that I might not be using myself.

**Comment by LouisCAD** [comment]
BTW, what's the reason you programmed it to not run when on the default (main) branch?

**Comment by yschimke** [comment]
I didn't think having it make changes to main was safe. But it's manual, so up to you

**Comment by yschimke** [comment]
> Hum… this mismatch is not such an ideal situation…
> I'd like the workflow to not be so dependent on GitHub actions or a specific desktop OS that I might not be using myself.
> 

I don't have a good solution then.

Options

This) Linux is canonical and updated in CI
B) relax tolerances so pass on both, and refresh occasionally in CI
C) make Mac the master and change runner?

Don't test screenshots in CI, just update locally

**Comment by LouisCAD** [comment]
@yschimke I think I'd be happy with option B, but I don't know where/how to setup that tolerance, and which number to give it.
Do you have any clue?

**Comment by yschimke** [comment]
Yep, will do.

**Comment by yschimke** [comment]
0.01 or 1% but can be tuned.

If you temporarily set it to 0, and run verifyRoborazziDebug, you'll see the diffs. It's mostly antialiasing of curves etc.

**Comment by LouisCAD** [comment]
Thank you very much, Yuri!

That's a very welcome addition (plus it's fixing the CI 😄)

**Pull request merged**
